### ISSUE TITLE
port folders

### ISSUE THREAD

**Issue by mitchweaver** [bonsai-linux/bonsai#17]
currently ports are just in one big folder, this is already messy at ~60 ports -- can't imagine how cluttered it would be at 1000+

Some distros don't seem to think this is a problem, but I think it is.

Folder support such as `core`, `opt`, `contrib` as the likes of CRUX Linux or a similar style would be nice. Not sure how I want this implemented, just wanted to make this issue to note that is on the radar.

**Comment by trvv** [comment]
It could be super cool to do a tagging-esque system, by having a central directory like `direct` and then having another directory like `tags` which contains folders with package types that contain symlinks to specific packages, in case there are packages that have similar or overlapping categories. idk, just a thought

**Comment by mitchweaver** [comment]
closed by rewrite, #89
