### ISSUE TITLE
Ports: Wishlist

### ISSUE THREAD

**Issue by mitchweaver** [bonsai-linux/bonsai#21]
Use this issue to discuss ports that you wish to be added.

----

- [ ] ghc
- [ ] go
- [x] python3
- [ ] python2
- [ ] openvpn
- [x] dropbear 
- [ ] neovim
- [x] netcat
- [ ] socat
- [ ] nfs-utils
- [ ] fff <-- (once we get the `libedit` patch upstream)
- [ ] ranger (needs mouse support patched out for netbsd-curses)
- [ ] plan9port
- [ ] gnupg
- [ ] offlineimap
- [ ] neomutt
- [x] htop

**Comment by PaperMountainStudio** [comment]
- [ ] nvi
- [ ] vis
- [ ] lua
- [ ] scron
- [ ] tree

**Comment by lucat1** [comment]
Tree is already available

**Comment by PaperMountainStudio** [comment]
@lucat1 Oh. I see now.

**Comment by protonesso** [comment]
Midnight commander and gpm

**Comment by protonesso** [comment]
gnu Moe, zile, emacs

**Comment by protonesso** [comment]
lzip, zstd, lz4

**Comment by mininmobile** [comment]
qjs and npm (node is thicc, maybe later)

**Comment by strikersh** [comment]
- [ ] shadow-utils (for useradd, usermod, chsh, etc.)
- [ ] zsh
- [ ] bash
- [ ] rustup/rust
- [ ] pash
- [ ] s-tui
- [ ] openjdk (Voidlinux musl have issue with it but alpine can build it)
