### ISSUE TITLE
Xorg roadmap

### ISSUE THREAD

**Issue by lucat1** [bonsai-linux/bonsai#27]
- [ ] [`xorg-server`](https://pkgs.alpinelinux.org/package/edge/main/x86/xorg-server)
- fontconfig and font stuff
- - [x] [`libdrm`](https://pkgs.alpinelinux.org/package/edge/main/x86/libdrm)
- - - [x] [`libpciaccess`](https://pkgs.alpinelinux.org/package/edge/main/x86/libpciaccess)
- - [x] smdev
- - [ ] [`libepoxy`](https://pkgs.alpinelinux.org/package/edge/main/x86/libepoxy)
- - [x] [`lixau`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxau)
- - [x] [`libxdmcp`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxdmcp)
- - - [x] [`libbsd`](https://pkgs.alpinelinux.org/package/edge/main/x86/libbsd)
- - [x] [`libxfont2`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxfont2)
- - - [x] [`freetype`](https://pkgs.alpinelinux.org/package/edge/main/x86/freetype)
- - - - [x] [`libbz2`](https://pkgs.alpinelinux.org/package/edge/main/x86/libbz2)
- - - - [x] [`libpng`](https://pkgs.alpinelinux.org/package/edge/main/x86/libpng)
- - - [x] [`libfontenc`](https://pkgs.alpinelinux.org/package/edge/main/x86/libfontenc)
- - [x] [`libxshmfence`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxshmfence)
- all mesa + gl stuff
- - [x] [`pixman`](https://pkgs.alpinelinux.org/package/edge/main/x86/pixman)
- - [x] [`xkeyboard-config`](https://pkgs.alpinelinux.org/package/edge/main/x86/xkeyboard-config)
- - [x] [`xkbcomp`](https://pkgs.alpinelinux.org/package/edge/main/x86/xkbcomp)
- - - [x] [`libx11`](https://pkgs.alpinelinux.org/package/edge/main/x86/libx11)
- - - - [x] [`libxcb`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxcb)
- - - [x] [`libxkbfile`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxkbfile)
- - [x] [`xinit`](https://pkgs.alpinelinux.org/package/edge/main/x86/xinit)
- - - `util-linux` or just [`mcookie`](https://pkgs.alpinelinux.org/package/edge/main/x86/mcookie)
 - - - [x] [`xauth`](https://pkgs.alpinelinux.org/package/edge/main/x86/xauth)
- - - - [x] [`libxext`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxext)
- - - - [x] [`libxmu`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxmu)
- - - - - [x] [`libxt`](https://pkgs.alpinelinux.org/package/edge/main/x86/libxt)
- - - - - - [x] [`libsm`](https://pkgs.alpinelinux.org/package/edge/main/x86/libsm)
- - - - - - - [x] [`libuuid`](https://pkgs.alpinelinux.org/package/edge/main/x86/libuuid)
- - - - - - [x] [`libice`](https://pkgs.alpinelinux.org/package/edge/main/x86/libice)
- - - - [x] [`xmodmap`](https://pkgs.alpinelinux.org/package/edge/main/x86/xmodmap)
- - - - [x] [`xrdb`](https://pkgs.alpinelinux.org/package/edge/main/x86/xrdb)
- - - - - [x] [`mcpp`](https://pkgs.alpinelinux.org/package/edge/main/x86/mcpp) ??

**Comment by PaperMountainStudio** [comment]
[ ] xinerama
[ ] xft
