### ISSUE TITLE
(future): recursive dep handling for delpkg()

### ISSUE THREAD

**Issue by mitchweaver** [bonsai-linux/bonsai#4]
dependency handling works for adding packages, recursively gathering and adding the needed packages

it would be nice if this were the same for the delpkg() function

Note:

1. only remove packages if they are orphans ie they have NO other packages depending on them
2. Do not remove packages if they are part of a meta package such as `core-system`, (we dont want to remove our shell, coreutils, etc...)

**Comment by trvv** [comment]
what about packages that also provide commands? i.e. ImageMagick might be a dependency for only one thing and when you delete that package you also delete all the ImageMagicks tools that come with it?

**Comment by mitchweaver** [comment]
@trvv this is just one of the problems you encounter with dep handling

An even better example would be `neofetch`. It requires bash, but say you are using bash as your system shell. 

If nothing else depends on bash, the pkg mgr would say "Hey, we found an orphaned package!" -- and remove bash, thus breaking your system.

I don't know a perfect solution to this, one way its often done is flags/pkgfile variables that "prevent" a package from being deleted, (ex: this is how crux does it). But this looks dirty imo, perhaps there's a better solution.

:woman_shrugging: one solution is to just not provide dep handling on deletion, leave it to the user to know what packages they still need or not. Not sure how popular that would be

**Comment by trvv** [comment]
I'd be down to have that manually be done, but it wouldn't be too bad if there was a nuclear option that just recursively wiped every non-essential package that wasn't a dep for something else just in case I get in too deep

**Comment by mininmobile** [comment]
idea: by default the package manager checks a flag on that package saying that the user decided to install this. the user could also manually uncheck the flag. let's go back to the `neofetch` example: if you do `bs bash` and then `bs neofetch`, bash will not be a dependency, or won't be seen by the system as such. when you do uninstall neofetch, it will not take bash with it. let's say you are building a package manually, you need to install the dependencies before building but you will have to uninstall them manually later, no good, if you install the dependencies like `bs -d depOne depTwo depThree ...` then upon uninstall of the main package it will detect if its dependencies are marked as dependencies, used by nothing else, etc., and then uninstall them if it does/doesn't match the tests. if a package is being installed from the repo then the "-d" flag is checked behind the scenes.

**Comment by trvv** [comment]
that's a cool idea but might be confusing for new users

-------- Original Message --------
