### ISSUE TITLE
Suggest your CFLAGS / LDFLAGS / etc

### ISSUE THREAD

**Issue by mitchweaver** [bonsai-linux/bonsai#5]
Always looking for good suggestions for more global flags to add to our `.rc`

Keep in mind these will be GLOBAL. So they must be sane, (ie not cause breakage).

Post them here for discussion / review.

**Comment by kaewhyes** [comment]
``-j$((`nproc` - 1))``? Will use all available threads, except for one

**Comment by mitchweaver** [comment]
@kaewhyes `nproc` is not guaranteed to be a command, for instance on `bonsai` it is not a command.

This is much more portable: 
```bash
jobs=$(grep -c 'cpu cores' /proc/cpuinfo 2>/dev/null)
: ${jobs:=1}
````

As for "except for one", I personally prefer to use them all. You're trading speed over system responsiveness during compilation.

**Comment by kaewhyes** [comment]
Sounds good to me, I like the portable version a lot. When im compiling
things, I'll normally be doing other things, which is why I'm using nproc -
1.

**Comment by Sacules** [comment]
`-march=native` and `-O2` work pretty well, and are recommended in the Gentoo wiki.

**Comment by mitchweaver** [comment]
@Sacules `-march=native` is commented out in the `bonsai.rc`, stating it will be a performance boost but it makes your binaries unportable to other systems.

We use `-Os` instead of `-O2` because we are static linking, we want to optimize for size as that is its largest downside.
