### ISSUE TITLE
imlib2 dependent programs cannot be statically linked

### ISSUE THREAD

**Issue by mitchweaver** [bonsai-linux/bonsai#90]
![imlib2](http://bonsai-linux.org/uploads/aYk5h.png)

https://github.com/bonsai-linux/bonsai/blob/master/ports/shared/README.md

**Comment by mitchweaver** [comment]
http://bonsai-linux.org/uploads/KaM8W.png

possible answer

**Comment by protonesso** [comment]
@mitchweaver why rewrite?
